## Configuracion de Spring
spring:
  application:
    name: ms-productos-busqueda
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tienda}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

## Configuracion de Instancia
server:
  port: 8090
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}
  gatewayAddres: ${HOST_GATEWAY:http://localhost}:${PORT_GATEWAY}:8762/ms-productos-busqueda


## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-productos-busqueda

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE
